/**
 * OFFICIAL LABRUTE CONSTANTS
 * All enums and constants from the original game
 */

const SkillName = {
  herculeanStrength: 'herculeanStrength',
  felineAgility: 'felineAgility',
  lightningBolt: 'lightningBolt',
  vitality: 'vitality',
  immortal: 'immortal',
  weaponsMaster: 'weaponsMaster',
  martialArts: 'martialArts',
  sixthSense: 'sixthSense',
  hostility: 'hostility',
  fistsOfFury: 'fistsOfFury',
  shield: 'shield',
  armor: 'armor',
  toughenedSkin: 'toughenedSkin',
  untouchable: 'untouchable',
  sabotage: 'sabotage',
  shock: 'shock',
  bodybuilder: 'bodybuilder',
  relentless: 'relentless',
  survival: 'survival',
  leadSkeleton: 'leadSkeleton',
  balletShoes: 'balletShoes',
  determination: 'determination',
  firstStrike: 'firstStrike',
  resistant: 'resistant',
  counterAttack: 'counterAttack',
  ironHead: 'ironHead',
  thief: 'thief',
  fierceBrute: 'fierceBrute',
  tragicPotion: 'tragicPotion',
  net: 'net',
  bomb: 'bomb',
  hammer: 'hammer',
  cryOfTheDamned: 'cryOfTheDamned',
  hypnosis: 'hypnosis',
  flashFlood: 'flashFlood',
  tamer: 'tamer',
  regeneration: 'regeneration',
  chef: 'chef',
  spy: 'spy',
  saboteur: 'saboteur',
  backup: 'backup',
  hideaway: 'hideaway',
  monk: 'monk',
  vampirism: 'vampirism',
  chaining: 'chaining',
  haste: 'haste',
  treat: 'treat',
  repulse: 'repulse',
};

const WeaponName = {
  axe: 'axe',
  baton: 'baton',
  broadsword: 'broadsword',
  bumps: 'bumps',
  fan: 'fan',
  flail: 'flail',
  fryingPan: 'fryingPan',
  halbard: 'halbard',
  hatchet: 'hatchet',
  keyboard: 'keyboard',
  knife: 'knife',
  lance: 'lance',
  leek: 'leek',
  mammothBone: 'mammothBone',
  morningStar: 'morningStar',
  mug: 'mug',
  noodleBowl: 'noodleBowl',
  piopio: 'piopio',
  racquet: 'racquet',
  sai: 'sai',
  scimitar: 'scimitar',
  shuriken: 'shuriken',
  sword: 'sword',
  trident: 'trident',
  trombone: 'trombone',
  whip: 'whip',
};

const PetName = {
  dog: 'dog',
  bear: 'bear',
  panther: 'panther',
};

const FightStat = {
  STRENGTH: 'STRENGTH',
  AGILITY: 'AGILITY',
  SPEED: 'SPEED',
  ENDURANCE: 'ENDURANCE',
  INTELLIGENCE: 'INTELLIGENCE',
  WILLPOWER: 'WILLPOWER',
  DEXTERITY: 'DEXTERITY',
  CRITICAL_CHANCE: 'CRITICAL_CHANCE',
  CRITICAL_DAMAGE: 'CRITICAL_DAMAGE',
  EVASION: 'EVASION',
  ACCURACY: 'ACCURACY',
  DISARM: 'DISARM',
  COMBO: 'COMBO',
  DEFLECT: 'DEFLECT',
  ARMOR: 'ARMOR',
  DAMAGE: 'DAMAGE',
  HIT_SPEED: 'HIT_SPEED',
  INITIATIVE: 'INITIATIVE',
  STRENGTH_MODIFIER: 'STRENGTH_MODIFIER',
  AGILITY_MODIFIER: 'AGILITY_MODIFIER',
  SPEED_MODIFIER: 'SPEED_MODIFIER',
  COUNTER: 'COUNTER',
  REVERSAL: 'REVERSAL',
  BLOCK: 'BLOCK',
  REACH: 'REACH',
};

module.exports = {
  SkillName,
  WeaponName,
  PetName,
  FightStat,
};