/**
 * OFFICIAL LABRUTE WEAPONS DATA
 * 100% accurate values from the original game
 * Source: fichiers_labrute-officiel/labrute/core/src/brute/weapons.ts
 */

const WeaponName = {
  axe: 'axe',
  baton: 'baton',
  broadsword: 'broadsword',
  bumps: 'bumps',
  fan: 'fan',
  flail: 'flail',
  fryingPan: 'fryingPan',
  halbard: 'halbard',
  hatchet: 'hatchet',
  keyboard: 'keyboard',
  knife: 'knife',
  lance: 'lance',
  leek: 'leek',
  mammothBone: 'mammothBone',
  morningStar: 'morningStar',
  mug: 'mug',
  noodleBowl: 'noodleBowl',
  piopio: 'piopio',
  racquet: 'racquet',
  sai: 'sai',
  scimitar: 'scimitar',
  shuriken: 'shuriken',
  sword: 'sword',
  trident: 'trident',
  trombone: 'trombone',
  whip: 'whip',
};

const WeaponType = {
  FAST: 'fast',
  SHARP: 'sharp',
  HEAVY: 'heavy',
  LONG: 'long',
  THROWN: 'thrown',
  BLUNT: 'blunt',
};

// OFFICIAL WEAPON DATA - DO NOT MODIFY!
const weapons = [
  {
    name: 'axe',
    odds: 3,
    types: ['heavy', 'blunt'],
    tempo: 2.3,
    reversal: -0.2,
    evasion: -0.4,
    dexterity: -0.8,
    block: -0.5,
    accuracy: 0.5,
    disarm: 0.1,
    combo: -0.4,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 55,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'baton',
    odds: 70,
    types: ['long'],
    tempo: 1,
    reversal: 0.3,
    evasion: 0.05,
    dexterity: 0,
    block: 0.25,
    accuracy: 0,
    disarm: 0.25,
    combo: 0.1,
    deflect: 0,
    criticalChance: 0.2,
    criticalDamage: 0,
    damage: 6,
    toss: 3,
    reach: 3,
    animation: 'estoc',
  },
  {
    name: 'broadsword',
    odds: 100,
    types: ['sharp'],
    tempo: 1.2,
    reversal: 0.1,
    evasion: 0,
    dexterity: 0,
    block: 0.15,
    accuracy: 0,
    disarm: 0.15,
    combo: 0,
    deflect: 0,
    criticalChance: 0.3,
    criticalDamage: 0,
    damage: 10,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'bumps',
    odds: 50,
    types: ['heavy', 'blunt'],
    tempo: 2,
    reversal: -0.3,
    evasion: -0.3,
    dexterity: -0.65,
    block: -0.3,
    accuracy: 0.3,
    disarm: 0.1,
    combo: -0.6,
    deflect: 0,
    criticalChance: 0.2,
    criticalDamage: 0,
    damage: 30,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'fan',
    odds: 2,
    types: ['fast'],
    tempo: 0.28,
    reversal: 0.5,
    evasion: 0.6,
    dexterity: 0.5,
    block: -0.5,
    accuracy: 0,
    disarm: -0.5,
    combo: 0.45,
    deflect: 0.25,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 4,
    toss: 5,
    reach: 0,
    animation: 'slash',
  },
  {
    name: 'flail',
    odds: 4,
    types: ['heavy', 'blunt'],
    tempo: 2.2,
    reversal: 0,
    evasion: -0.3,
    dexterity: -0.5,
    block: -0.1,
    accuracy: 0.5,
    disarm: 0.1,
    combo: -0.4,
    deflect: 0,
    criticalChance: 0.3,
    criticalDamage: 0,
    damage: 36,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'fryingPan',
    odds: 40,
    types: ['heavy', 'blunt'],
    tempo: 1.2,
    reversal: 0.3,
    evasion: 0.2,
    dexterity: -0.4,
    block: 0.2,
    accuracy: 0,
    disarm: 0,
    combo: 0,
    deflect: 0,
    criticalChance: 0.5,
    criticalDamage: 0,
    damage: 17,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'halbard',
    odds: 3,
    types: ['long', 'sharp'],
    tempo: 1.8,
    reversal: 0,
    evasion: -0.3,
    dexterity: -0.2,
    block: 0.1,
    accuracy: 0.2,
    disarm: 0.3,
    combo: -0.2,
    deflect: 0,
    criticalChance: 0.1,
    criticalDamage: 0,
    damage: 24,
    toss: 8,
    reach: 4,
    animation: 'slash',
  },
  {
    name: 'hatchet',
    odds: 40,
    types: ['sharp', 'thrown'],
    tempo: 1,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0,
    disarm: 0,
    combo: 0,
    deflect: 0,
    criticalChance: 0.1,
    criticalDamage: 0,
    damage: 8,
    toss: 15,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'keyboard',
    odds: 30,
    types: ['fast', 'blunt'],
    tempo: 0.7,
    reversal: 0.2,
    evasion: 0.4,
    dexterity: 0.3,
    block: 0,
    accuracy: 0,
    disarm: -0.2,
    combo: 0.5,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 7,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'knife',
    odds: 80,
    types: ['fast', 'sharp'],
    tempo: 0.6,
    reversal: 0.45,
    evasion: 0.3,
    dexterity: 0.5,
    block: -0.3,
    accuracy: 0,
    disarm: -0.3,
    combo: 0.3,
    deflect: 0,
    criticalChance: 0.3,
    criticalDamage: 0,
    damage: 7,
    toss: 10,
    reach: 0,
    animation: 'estoc',
  },
  {
    name: 'lance',
    odds: 30,
    types: ['long'],
    tempo: 1.4,
    reversal: 0,
    evasion: -0.1,
    dexterity: -0.1,
    block: 0,
    accuracy: 0.3,
    disarm: 0.1,
    combo: 0,
    deflect: 0,
    criticalChance: 0.15,
    criticalDamage: 0,
    damage: 12,
    toss: 6,
    reach: 5,
    animation: 'estoc',
  },
  {
    name: 'leek',
    odds: 20,
    types: ['fast', 'blunt'],
    tempo: 0.5,
    reversal: 0.5,
    evasion: 0.5,
    dexterity: 1,
    block: 0,
    accuracy: 0,
    disarm: -0.5,
    combo: 0.4,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 5,
    toss: 5,
    reach: 2,
    animation: 'slash',
  },
  {
    name: 'mammothBone',
    odds: 1,
    types: ['heavy', 'blunt'],
    tempo: 3,
    reversal: -0.5,
    evasion: -0.5,
    dexterity: -1.5,
    block: -0.5,
    accuracy: 1.5,
    disarm: 0.5,
    combo: -0.8,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 55,
    toss: 10,
    reach: 2,
    animation: 'slash',
  },
  {
    name: 'morningStar',
    odds: 5,
    types: ['heavy', 'blunt'],
    tempo: 2.5,
    reversal: -0.1,
    evasion: -0.3,
    dexterity: -0.8,
    block: -0.3,
    accuracy: 0.5,
    disarm: 0.1,
    combo: -0.45,
    deflect: 0,
    criticalChance: 0.1,
    criticalDamage: 0,
    damage: 45,
    toss: 5,
    reach: 2,
    animation: 'slash',
  },
  {
    name: 'mug',
    odds: 50,
    types: ['fast'],
    tempo: 0.5,
    reversal: 0.3,
    evasion: 0.15,
    dexterity: 0.5,
    block: 0,
    accuracy: 0,
    disarm: -0.1,
    combo: 0.4,
    deflect: 0,
    criticalChance: 0.5,
    criticalDamage: 0,
    damage: 5,
    toss: 5,
    reach: 0,
    animation: 'slash',
  },
  {
    name: 'noodleBowl',
    odds: 15,
    types: ['thrown'],
    tempo: 0.6,
    reversal: 0.3,
    evasion: 0.3,
    dexterity: 0.5,
    block: 0,
    accuracy: 0,
    disarm: -0.3,
    combo: 0.35,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 10,
    toss: 30,
    reach: 0,
    animation: 'fist',
  },
  {
    name: 'piopio',
    odds: 8,
    types: ['thrown'],
    tempo: 1,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0.5,
    disarm: 0,
    combo: 0,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 5,
    toss: 50,
    reach: 0,
    animation: 'fist',
  },
  {
    name: 'racquet',
    odds: 20,
    types: ['fast', 'blunt'],
    tempo: 0.8,
    reversal: 0.4,
    evasion: 0.3,
    dexterity: 0.4,
    block: 0,
    accuracy: 0,
    disarm: -0.3,
    combo: 0.4,
    deflect: 0.3,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 7,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'sai',
    odds: 10,
    types: ['fast', 'sharp'],
    tempo: 0.5,
    reversal: 0.3,
    evasion: 0.5,
    dexterity: 0.7,
    block: 0.5,
    accuracy: 0,
    disarm: 0.5,
    combo: 0.3,
    deflect: 0,
    criticalChance: 0.15,
    criticalDamage: 0,
    damage: 8,
    toss: 8,
    reach: 0,
    animation: 'estoc',
  },
  {
    name: 'scimitar',
    odds: 6,
    types: ['sharp'],
    tempo: 0.8,
    reversal: 0.2,
    evasion: 0.2,
    dexterity: 0.2,
    block: 0.1,
    accuracy: 0,
    disarm: 0.1,
    combo: 0.05,
    deflect: 0,
    criticalChance: 0.35,
    criticalDamage: 0,
    damage: 9,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'shuriken',
    odds: 8,
    types: ['thrown'],
    tempo: 0.15,
    reversal: 0.8,
    evasion: 0.2,
    dexterity: 1,
    block: 0,
    accuracy: 0,
    disarm: 0,
    combo: 0.6,
    deflect: 0,
    criticalChance: 0,
    criticalDamage: 0,
    damage: 3,
    toss: 80,
    reach: 0,
    animation: 'fist',
  },
  {
    name: 'sword',
    odds: 10,
    types: ['sharp'],
    tempo: 1,
    reversal: 0.15,
    evasion: 0.05,
    dexterity: 0.05,
    block: 0.18,
    accuracy: 0,
    disarm: 0.18,
    combo: 0.03,
    deflect: 0,
    criticalChance: 0.25,
    criticalDamage: 0,
    damage: 8,
    toss: 5,
    reach: 1,
    animation: 'slash',
  },
  {
    name: 'trident',
    odds: 8,
    types: ['long'],
    tempo: 1.5,
    reversal: -0.1,
    evasion: -0.1,
    dexterity: -0.1,
    block: 0.2,
    accuracy: 0.3,
    disarm: 0.2,
    combo: -0.1,
    deflect: 0,
    criticalChance: 0.1,
    criticalDamage: 0,
    damage: 14,
    toss: 8,
    reach: 3,
    animation: 'estoc',
  },
  {
    name: 'trombone',
    odds: 1,
    types: ['heavy', 'blunt'],
    tempo: 2,
    reversal: 0.5,
    evasion: -0.3,
    dexterity: -0.8,
    block: -0.3,
    accuracy: 0.3,
    disarm: 0.1,
    combo: -0.4,
    deflect: 0,
    criticalChance: 0.2,
    criticalDamage: 0,
    damage: 25,
    toss: 5,
    reach: 2,
    animation: 'slash',
  },
  {
    name: 'whip',
    odds: 3,
    types: ['long'],
    tempo: 1.4,
    reversal: -0.1,
    evasion: -0.2,
    dexterity: 0.3,
    block: -0.2,
    accuracy: 0.3,
    disarm: 0.4,
    combo: -0.1,
    deflect: 0,
    criticalChance: 0.3,
    criticalDamage: 0,
    damage: 10,
    toss: 4,
    reach: 7,
    animation: 'whip',
  },
];

// Helper function to get weapon by name
const getWeapon = (name) => {
  return weapons.find(w => w.name === name);
};

// Limited weapons (can't have too many of these)
const limitedWeapons = [
  'knife', 'broadsword', 'lance', 'baton', 'trident', 'hatchet',
  'scimitar', 'axe', 'sword', 'fan', 'shuriken', 'bumps',
  'morningStar', 'mammothBone', 'flail', 'whip',
];

module.exports = {
  WeaponName,
  WeaponType,
  weapons,
  getWeapon,
  limitedWeapons,
};